import type { Metadata, Viewport } from 'next'
import { Geist_Mono, Inter } from 'next/font/google'
import { headers } from 'next/headers'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getTranslations } from 'next-intl/server'
import type { ReactNode } from 'react'

import '@workspace/ui/globals.css'
import { cn } from '@workspace/ui/lib/utils'

import { Providers } from '@/components/providers'
import { siteConfig } from '@/lib/site-config'

const fontSans = Inter({ subsets: ['latin'], variable: '--font-sans' })
const fontMono = Geist_Mono({ subsets: ['latin'], variable: '--font-mono' })

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#09090b' },
  ],
  width: 'device-width',
  initialScale: 1,
}

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations('Metadata')
  const title = t('title')
  const description = t('description')

  return {
    // ── Basic ──────────────────────────────────────────────────────────────
    title: {
      default: title,
      template: `%s · ${title}`,
    },
    description,
    applicationName: siteConfig.name,
    generator: undefined, // Never expose the tech stack.
    referrer: 'strict-origin-when-cross-origin',

    // ── Canonical & alternates ─────────────────────────────────────────────
    alternates: {
      canonical: siteConfig.canonicalBase,
      languages: Object.fromEntries(
        siteConfig.locale.supported.map((locale) => [
          locale,
          `${siteConfig.canonicalBase}/${locale}`,
        ])
      ),
    },

    // ── Open Graph ─────────────────────────────────────────────────────────
    openGraph: {
      type: 'website',
      siteName: siteConfig.name,
      title,
      description,
      url: siteConfig.url,
      locale: siteConfig.locale.default,
      images: [
        {
          url: siteConfig.ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },

    // ── X / Twitter Cards ──────────────────────────────────────────────────
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [siteConfig.ogImage],
      ...(siteConfig.links.twitter.length > 0
        ? { site: siteConfig.links.twitter }
        : {}),
    },

    // ── Icons & PWA ────────────────────────────────────────────────────────
    icons: {
      icon: [
        { url: '/favicon.ico', sizes: 'any' },
        { url: '/icon-192.png', type: 'image/png', sizes: '192x192' },
        { url: '/icon-512.png', type: 'image/png', sizes: '512x512' },
      ],
      apple: '/apple-touch-icon.png',
      shortcut: '/favicon.ico',
    },
    // The web manifest is generated by `app/manifest.ts`; Next injects the
    // <link rel="manifest"> tag automatically (served at /manifest.webmanifest).

    // ── Search engine verification ─────────────────────────────────────────
    // Set NEXT_PUBLIC_GSC_VERIFICATION and NEXT_PUBLIC_BING_VERIFICATION in .env
    verification: {
      ...(siteConfig.analytics.googleSearchConsoleVerification
        ? { google: siteConfig.analytics.googleSearchConsoleVerification }
        : {}),
      ...(siteConfig.analytics.bingVerification
        ? {
            other: { 'msvalidate.01': [siteConfig.analytics.bingVerification] },
          }
        : {}),
    },

    // ── Robots ────────────────────────────────────────────────────────────
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
  }
}

/** Schema.org WebSite structured data — helps search engines understand the site. */
function WebsiteJsonLd() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: siteConfig.name,
    url: siteConfig.url,
    description: siteConfig.description,
    inLanguage: siteConfig.locale.default,
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${siteConfig.url}/search?q={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  }
  return (
    <script
      type='application/ld+json'
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
  )
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  const locale = await getLocale()
  // Per-request CSP nonce set by proxy.ts; forwarded to next-themes.
  const nonce = (await headers()).get('x-nonce')

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={cn(fontSans.variable, fontMono.variable)}
    >
      <head>
        <WebsiteJsonLd />
        {/* Google Tag Manager — activated when NEXT_PUBLIC_GTM_ID is set.
            To use the @next/third-parties GoogleTagManager component instead,
            add @next/third-parties to web/package.json and update this block. */}
        {siteConfig.analytics.googleTagManagerId ? (
          // eslint-disable-next-line @next/next/next-script-for-ga
          <script
            dangerouslySetInnerHTML={{
              __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${siteConfig.analytics.googleTagManagerId}');`,
            }}
          />
        ) : null}
      </head>
      <body className='font-sans antialiased'>
        {/* GTM noscript fallback */}
        {siteConfig.analytics.googleTagManagerId ? (
          <noscript>
            <iframe
              src={`https://www.googletagmanager.com/ns.html?id=${siteConfig.analytics.googleTagManagerId}`}
              height='0'
              width='0'
              style={{ display: 'none', visibility: 'hidden' }}
            />
          </noscript>
        ) : null}
        <NextIntlClientProvider>
          <Providers {...(nonce ? { nonce } : {})}>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
