CREATE TABLE public.countries (
  iso2 char(2) PRIMARY KEY,
  iso3 char(3) NOT NULL UNIQUE,
  numeric_code char(3) NOT NULL,
  name text NOT NULL,
  official_name text NOT NULL,
  region text,
  subregion text,
  capital text,
  calling_code text,
  flag_emoji text,
  tld text,
  currency_code char(3) REFERENCES public.currencies (code)
);

CREATE INDEX countries_region_idx ON public.countries (region);
CREATE INDEX countries_currency_code_idx ON public.countries (currency_code);
CREATE INDEX countries_name_trgm_idx ON public.countries USING gin (name gin_trgm_ops);

INSERT INTO public.countries (iso2, iso3, numeric_code, name, official_name, region, subregion, capital, calling_code, flag_emoji, tld, currency_code) VALUES
  ('AD', 'AND', '020', 'Andorra', 'Principality of Andorra', 'Europe', 'Southern Europe', 'Andorra la Vella', '+376', '🇦🇩', '.ad', 'EUR'),
  ('AE', 'ARE', '784', 'United Arab Emirates', 'United Arab Emirates', 'Asia', 'Western Asia', 'Abu Dhabi', '+971', '🇦🇪', '.ae', 'AED'),
  ('AF', 'AFG', '004', 'Afghanistan', 'Islamic Republic of Afghanistan', 'Asia', 'Southern Asia', 'Kabul', '+93', '🇦🇫', '.af', 'AFN'),
  ('AG', 'ATG', '028', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Americas', 'Caribbean', 'Saint John''s', '+1268', '🇦🇬', '.ag', 'XCD'),
  ('AI', 'AIA', '660', 'Anguilla', 'Anguilla', 'Americas', 'Caribbean', 'The Valley', '+1264', '🇦🇮', '.ai', 'XCD'),
  ('AL', 'ALB', '008', 'Albania', 'Republic of Albania', 'Europe', 'Southeast Europe', 'Tirana', '+355', '🇦🇱', '.al', 'ALL'),
  ('AM', 'ARM', '051', 'Armenia', 'Republic of Armenia', 'Asia', 'Western Asia', 'Yerevan', '+374', '🇦🇲', '.am', 'AMD'),
  ('AO', 'AGO', '024', 'Angola', 'Republic of Angola', 'Africa', 'Middle Africa', 'Luanda', '+244', '🇦🇴', '.ao', 'AOA'),
  ('AQ', 'ATA', '010', 'Antarctica', 'Antarctica', 'Antarctic', NULL, NULL, NULL, '🇦🇶', '.aq', NULL),
  ('AR', 'ARG', '032', 'Argentina', 'Argentine Republic', 'Americas', 'South America', 'Buenos Aires', '+54', '🇦🇷', '.ar', 'ARS'),
  ('AS', 'ASM', '016', 'American Samoa', 'American Samoa', 'Oceania', 'Polynesia', 'Pago Pago', '+1684', '🇦🇸', '.as', 'USD'),
  ('AT', 'AUT', '040', 'Austria', 'Republic of Austria', 'Europe', 'Central Europe', 'Vienna', '+43', '🇦🇹', '.at', 'EUR'),
  ('AU', 'AUS', '036', 'Australia', 'Commonwealth of Australia', 'Oceania', 'Australia and New Zealand', 'Canberra', '+61', '🇦🇺', '.au', 'AUD'),
  ('AW', 'ABW', '533', 'Aruba', 'Aruba', 'Americas', 'Caribbean', 'Oranjestad', '+297', '🇦🇼', '.aw', 'AWG'),
  ('AX', 'ALA', '248', 'Åland Islands', 'Åland Islands', 'Europe', 'Northern Europe', 'Mariehamn', '+35818', '🇦🇽', '.ax', 'EUR'),
  ('AZ', 'AZE', '031', 'Azerbaijan', 'Republic of Azerbaijan', 'Asia', 'Western Asia', 'Baku', '+994', '🇦🇿', '.az', 'AZN'),
  ('BA', 'BIH', '070', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Europe', 'Southeast Europe', 'Sarajevo', '+387', '🇧🇦', '.ba', 'BAM'),
  ('BB', 'BRB', '052', 'Barbados', 'Barbados', 'Americas', 'Caribbean', 'Bridgetown', '+1246', '🇧🇧', '.bb', 'BBD'),
  ('BD', 'BGD', '050', 'Bangladesh', 'People''s Republic of Bangladesh', 'Asia', 'Southern Asia', 'Dhaka', '+880', '🇧🇩', '.bd', 'BDT'),
  ('BE', 'BEL', '056', 'Belgium', 'Kingdom of Belgium', 'Europe', 'Western Europe', 'Brussels', '+32', '🇧🇪', '.be', 'EUR'),
  ('BF', 'BFA', '854', 'Burkina Faso', 'Burkina Faso', 'Africa', 'Western Africa', 'Ouagadougou', '+226', '🇧🇫', '.bf', 'XOF'),
  ('BG', 'BGR', '100', 'Bulgaria', 'Republic of Bulgaria', 'Europe', 'Southeast Europe', 'Sofia', '+359', '🇧🇬', '.bg', 'BGN'),
  ('BH', 'BHR', '048', 'Bahrain', 'Kingdom of Bahrain', 'Asia', 'Western Asia', 'Manama', '+973', '🇧🇭', '.bh', 'BHD'),
  ('BI', 'BDI', '108', 'Burundi', 'Republic of Burundi', 'Africa', 'Eastern Africa', 'Gitega', '+257', '🇧🇮', '.bi', 'BIF'),
  ('BJ', 'BEN', '204', 'Benin', 'Republic of Benin', 'Africa', 'Western Africa', 'Porto-Novo', '+229', '🇧🇯', '.bj', 'XOF'),
  ('BL', 'BLM', '652', 'Saint Barthélemy', 'Collectivity of Saint Barthélemy', 'Americas', 'Caribbean', 'Gustavia', '+590', '🇧🇱', '.bl', 'EUR'),
  ('BM', 'BMU', '060', 'Bermuda', 'Bermuda', 'Americas', 'North America', 'Hamilton', '+1441', '🇧🇲', '.bm', 'BMD'),
  ('BN', 'BRN', '096', 'Brunei', 'Nation of Brunei, Abode of Peace', 'Asia', 'South-Eastern Asia', 'Bandar Seri Begawan', '+673', '🇧🇳', '.bn', 'BND'),
  ('BO', 'BOL', '068', 'Bolivia', 'Plurinational State of Bolivia', 'Americas', 'South America', 'Sucre', '+591', '🇧🇴', '.bo', 'BOB'),
  ('BQ', 'BES', '535', 'Caribbean Netherlands', 'Bonaire, Sint Eustatius and Saba', 'Americas', 'Caribbean', 'Kralendijk', '+599', NULL, '.bq', 'USD'),
  ('BR', 'BRA', '076', 'Brazil', 'Federative Republic of Brazil', 'Americas', 'South America', 'Brasília', '+55', '🇧🇷', '.br', 'BRL'),
  ('BS', 'BHS', '044', 'Bahamas', 'Commonwealth of the Bahamas', 'Americas', 'Caribbean', 'Nassau', '+1242', '🇧🇸', '.bs', 'BSD'),
  ('BT', 'BTN', '064', 'Bhutan', 'Kingdom of Bhutan', 'Asia', 'Southern Asia', 'Thimphu', '+975', '🇧🇹', '.bt', 'BTN'),
  ('BV', 'BVT', '074', 'Bouvet Island', 'Bouvet Island', 'Antarctic', NULL, NULL, '+47', '🇧🇻', '.bv', NULL),
  ('BW', 'BWA', '072', 'Botswana', 'Republic of Botswana', 'Africa', 'Southern Africa', 'Gaborone', '+267', '🇧🇼', '.bw', 'BWP'),
  ('BY', 'BLR', '112', 'Belarus', 'Republic of Belarus', 'Europe', 'Eastern Europe', 'Minsk', '+375', '🇧🇾', '.by', 'BYN'),
  ('BZ', 'BLZ', '084', 'Belize', 'Belize', 'Americas', 'Central America', 'Belmopan', '+501', '🇧🇿', '.bz', 'BZD'),
  ('CA', 'CAN', '124', 'Canada', 'Canada', 'Americas', 'North America', 'Ottawa', '+1', '🇨🇦', '.ca', 'CAD'),
  ('CC', 'CCK', '166', 'Cocos (Keeling) Islands', 'Territory of the Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand', 'West Island', '+61', '🇨🇨', '.cc', 'AUD'),
  ('CD', 'COD', '180', 'DR Congo', 'Democratic Republic of the Congo', 'Africa', 'Middle Africa', 'Kinshasa', '+243', '🇨🇩', '.cd', 'CDF'),
  ('CF', 'CAF', '140', 'Central African Republic', 'Central African Republic', 'Africa', 'Middle Africa', 'Bangui', '+236', '🇨🇫', '.cf', 'XAF'),
  ('CG', 'COG', '178', 'Republic of the Congo', 'Republic of the Congo', 'Africa', 'Middle Africa', 'Brazzaville', '+242', '🇨🇬', '.cg', 'XAF'),
  ('CH', 'CHE', '756', 'Switzerland', 'Swiss Confederation', 'Europe', 'Western Europe', 'Bern', '+41', '🇨🇭', '.ch', 'CHF'),
  ('CI', 'CIV', '384', 'Ivory Coast', 'Republic of Côte d''Ivoire', 'Africa', 'Western Africa', 'Yamoussoukro', '+225', '🇨🇮', '.ci', 'XOF'),
  ('CK', 'COK', '184', 'Cook Islands', 'Cook Islands', 'Oceania', 'Polynesia', 'Avarua', '+682', '🇨🇰', '.ck', NULL),
  ('CL', 'CHL', '152', 'Chile', 'Republic of Chile', 'Americas', 'South America', 'Santiago', '+56', '🇨🇱', '.cl', 'CLP'),
  ('CM', 'CMR', '120', 'Cameroon', 'Republic of Cameroon', 'Africa', 'Middle Africa', 'Yaoundé', '+237', '🇨🇲', '.cm', 'XAF'),
  ('CN', 'CHN', '156', 'China', 'People''s Republic of China', 'Asia', 'Eastern Asia', 'Beijing', '+86', '🇨🇳', '.cn', 'CNY'),
  ('CO', 'COL', '170', 'Colombia', 'Republic of Colombia', 'Americas', 'South America', 'Bogotá', '+57', '🇨🇴', '.co', 'COP'),
  ('CR', 'CRI', '188', 'Costa Rica', 'Republic of Costa Rica', 'Americas', 'Central America', 'San José', '+506', '🇨🇷', '.cr', 'CRC'),
  ('CU', 'CUB', '192', 'Cuba', 'Republic of Cuba', 'Americas', 'Caribbean', 'Havana', '+53', '🇨🇺', '.cu', 'CUC'),
  ('CV', 'CPV', '132', 'Cape Verde', 'Republic of Cabo Verde', 'Africa', 'Western Africa', 'Praia', '+238', '🇨🇻', '.cv', 'CVE'),
  ('CW', 'CUW', '531', 'Curaçao', 'Country of Curaçao', 'Americas', 'Caribbean', 'Willemstad', '+599', '🇨🇼', '.cw', 'ANG'),
  ('CX', 'CXR', '162', 'Christmas Island', 'Territory of Christmas Island', 'Oceania', 'Australia and New Zealand', 'Flying Fish Cove', '+61', '🇨🇽', '.cx', 'AUD'),
  ('CY', 'CYP', '196', 'Cyprus', 'Republic of Cyprus', 'Europe', 'Southern Europe', 'Nicosia', '+357', '🇨🇾', '.cy', 'EUR'),
  ('CZ', 'CZE', '203', 'Czechia', 'Czech Republic', 'Europe', 'Central Europe', 'Prague', '+420', '🇨🇿', '.cz', 'CZK'),
  ('DE', 'DEU', '276', 'Germany', 'Federal Republic of Germany', 'Europe', 'Western Europe', 'Berlin', '+49', '🇩🇪', '.de', 'EUR'),
  ('DJ', 'DJI', '262', 'Djibouti', 'Republic of Djibouti', 'Africa', 'Eastern Africa', 'Djibouti', '+253', '🇩🇯', '.dj', 'DJF'),
  ('DK', 'DNK', '208', 'Denmark', 'Kingdom of Denmark', 'Europe', 'Northern Europe', 'Copenhagen', '+45', '🇩🇰', '.dk', 'DKK'),
  ('DM', 'DMA', '212', 'Dominica', 'Commonwealth of Dominica', 'Americas', 'Caribbean', 'Roseau', '+1767', '🇩🇲', '.dm', 'XCD'),
  ('DO', 'DOM', '214', 'Dominican Republic', 'Dominican Republic', 'Americas', 'Caribbean', 'Santo Domingo', '+1', '🇩🇴', '.do', 'DOP'),
  ('DZ', 'DZA', '012', 'Algeria', 'People''s Democratic Republic of Algeria', 'Africa', 'Northern Africa', 'Algiers', '+213', '🇩🇿', '.dz', 'DZD'),
  ('EC', 'ECU', '218', 'Ecuador', 'Republic of Ecuador', 'Americas', 'South America', 'Quito', '+593', '🇪🇨', '.ec', 'USD'),
  ('EE', 'EST', '233', 'Estonia', 'Republic of Estonia', 'Europe', 'Northern Europe', 'Tallinn', '+372', '🇪🇪', '.ee', 'EUR'),
  ('EG', 'EGY', '818', 'Egypt', 'Arab Republic of Egypt', 'Africa', 'Northern Africa', 'Cairo', '+20', '🇪🇬', '.eg', 'EGP'),
  ('EH', 'ESH', '732', 'Western Sahara', 'Sahrawi Arab Democratic Republic', 'Africa', 'Northern Africa', 'El Aaiún', '+2', '🇪🇭', '.eh', 'DZD'),
  ('ER', 'ERI', '232', 'Eritrea', 'State of Eritrea', 'Africa', 'Eastern Africa', 'Asmara', '+291', '🇪🇷', '.er', 'ERN'),
  ('ES', 'ESP', '724', 'Spain', 'Kingdom of Spain', 'Europe', 'Southern Europe', 'Madrid', '+34', '🇪🇸', '.es', 'EUR'),
  ('ET', 'ETH', '231', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'Africa', 'Eastern Africa', 'Addis Ababa', '+251', '🇪🇹', '.et', 'ETB'),
  ('FI', 'FIN', '246', 'Finland', 'Republic of Finland', 'Europe', 'Northern Europe', 'Helsinki', '+358', '🇫🇮', '.fi', 'EUR'),
  ('FJ', 'FJI', '242', 'Fiji', 'Republic of Fiji', 'Oceania', 'Melanesia', 'Suva', '+679', '🇫🇯', '.fj', 'FJD'),
  ('FK', 'FLK', '238', 'Falkland Islands', 'Falkland Islands', 'Americas', 'South America', 'Stanley', '+500', '🇫🇰', '.fk', 'FKP'),
  ('FM', 'FSM', '583', 'Micronesia', 'Federated States of Micronesia', 'Oceania', 'Micronesia', 'Palikir', '+691', '🇫🇲', '.fm', NULL),
  ('FO', 'FRO', '234', 'Faroe Islands', 'Faroe Islands', 'Europe', 'Northern Europe', 'Tórshavn', '+298', '🇫🇴', '.fo', 'DKK'),
  ('FR', 'FRA', '250', 'France', 'French Republic', 'Europe', 'Western Europe', 'Paris', '+33', '🇫🇷', '.fr', 'EUR'),
  ('GA', 'GAB', '266', 'Gabon', 'Gabonese Republic', 'Africa', 'Middle Africa', 'Libreville', '+241', '🇬🇦', '.ga', 'XAF'),
  ('GB', 'GBR', '826', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'Europe', 'Northern Europe', 'London', '+44', '🇬🇧', '.uk', 'GBP'),
  ('GD', 'GRD', '308', 'Grenada', 'Grenada', 'Americas', 'Caribbean', 'St. George''s', '+1473', '🇬🇩', '.gd', 'XCD'),
  ('GE', 'GEO', '268', 'Georgia', 'Georgia', 'Asia', 'Western Asia', 'Tbilisi', '+995', '🇬🇪', '.ge', 'GEL'),
  ('GF', 'GUF', '254', 'French Guiana', 'Guiana', 'Americas', 'South America', 'Cayenne', '+594', '🇬🇫', '.gf', 'EUR'),
  ('GG', 'GGY', '831', 'Guernsey', 'Bailiwick of Guernsey', 'Europe', 'Northern Europe', 'St. Peter Port', '+44', '🇬🇬', '.gg', 'GBP'),
  ('GH', 'GHA', '288', 'Ghana', 'Republic of Ghana', 'Africa', 'Western Africa', 'Accra', '+233', '🇬🇭', '.gh', 'GHS'),
  ('GI', 'GIB', '292', 'Gibraltar', 'Gibraltar', 'Europe', 'Southern Europe', 'Gibraltar', '+350', '🇬🇮', '.gi', 'GIP'),
  ('GL', 'GRL', '304', 'Greenland', 'Greenland', 'Americas', 'North America', 'Nuuk', '+299', '🇬🇱', '.gl', 'DKK'),
  ('GM', 'GMB', '270', 'Gambia', 'Republic of the Gambia', 'Africa', 'Western Africa', 'Banjul', '+220', '🇬🇲', '.gm', 'GMD'),
  ('GN', 'GIN', '324', 'Guinea', 'Republic of Guinea', 'Africa', 'Western Africa', 'Conakry', '+224', '🇬🇳', '.gn', 'GNF'),
  ('GP', 'GLP', '312', 'Guadeloupe', 'Guadeloupe', 'Americas', 'Caribbean', 'Basse-Terre', '+590', '🇬🇵', '.gp', 'EUR'),
  ('GQ', 'GNQ', '226', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'Africa', 'Middle Africa', 'Malabo', '+240', '🇬🇶', '.gq', 'XAF'),
  ('GR', 'GRC', '300', 'Greece', 'Hellenic Republic', 'Europe', 'Southern Europe', 'Athens', '+30', '🇬🇷', '.gr', 'EUR'),
  ('GS', 'SGS', '239', 'South Georgia', 'South Georgia and the South Sandwich Islands', 'Antarctic', NULL, 'King Edward Point', '+500', '🇬🇸', '.gs', 'SHP'),
  ('GT', 'GTM', '320', 'Guatemala', 'Republic of Guatemala', 'Americas', 'Central America', 'Guatemala City', '+502', '🇬🇹', '.gt', 'GTQ'),
  ('GU', 'GUM', '316', 'Guam', 'Guam', 'Oceania', 'Micronesia', 'Hagåtña', '+1671', '🇬🇺', '.gu', 'USD'),
  ('GW', 'GNB', '624', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'Africa', 'Western Africa', 'Bissau', '+245', '🇬🇼', '.gw', 'XOF'),
  ('GY', 'GUY', '328', 'Guyana', 'Co-operative Republic of Guyana', 'Americas', 'South America', 'Georgetown', '+592', '🇬🇾', '.gy', 'GYD'),
  ('HK', 'HKG', '344', 'Hong Kong', 'Hong Kong Special Administrative Region of the People''s Republic of China', 'Asia', 'Eastern Asia', 'City of Victoria', '+852', '🇭🇰', '.hk', 'HKD'),
  ('HM', 'HMD', '334', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'Antarctic', NULL, NULL, NULL, '🇭🇲', '.hm', NULL),
  ('HN', 'HND', '340', 'Honduras', 'Republic of Honduras', 'Americas', 'Central America', 'Tegucigalpa', '+504', '🇭🇳', '.hn', 'HNL'),
  ('HR', 'HRV', '191', 'Croatia', 'Republic of Croatia', 'Europe', 'Southeast Europe', 'Zagreb', '+385', '🇭🇷', '.hr', 'EUR'),
  ('HT', 'HTI', '332', 'Haiti', 'Republic of Haiti', 'Americas', 'Caribbean', 'Port-au-Prince', '+509', '🇭🇹', '.ht', 'HTG'),
  ('HU', 'HUN', '348', 'Hungary', 'Hungary', 'Europe', 'Central Europe', 'Budapest', '+36', '🇭🇺', '.hu', 'HUF'),
  ('ID', 'IDN', '360', 'Indonesia', 'Republic of Indonesia', 'Asia', 'South-Eastern Asia', 'Jakarta', '+62', '🇮🇩', '.id', 'IDR'),
  ('IE', 'IRL', '372', 'Ireland', 'Republic of Ireland', 'Europe', 'Northern Europe', 'Dublin', '+353', '🇮🇪', '.ie', 'EUR'),
  ('IL', 'ISR', '376', 'Israel', 'State of Israel', 'Asia', 'Western Asia', 'Jerusalem', '+972', '🇮🇱', '.il', 'ILS'),
  ('IM', 'IMN', '833', 'Isle of Man', 'Isle of Man', 'Europe', 'Northern Europe', 'Douglas', '+44', '🇮🇲', '.im', 'GBP'),
  ('IN', 'IND', '356', 'India', 'Republic of India', 'Asia', 'Southern Asia', 'New Delhi', '+91', '🇮🇳', '.in', 'INR'),
  ('IO', 'IOT', '086', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa', 'Diego Garcia', '+246', '🇮🇴', '.io', 'USD'),
  ('IQ', 'IRQ', '368', 'Iraq', 'Republic of Iraq', 'Asia', 'Western Asia', 'Baghdad', '+964', '🇮🇶', '.iq', 'IQD'),
  ('IR', 'IRN', '364', 'Iran', 'Islamic Republic of Iran', 'Asia', 'Southern Asia', 'Tehran', '+98', '🇮🇷', '.ir', 'IRR'),
  ('IS', 'ISL', '352', 'Iceland', 'Iceland', 'Europe', 'Northern Europe', 'Reykjavik', '+354', '🇮🇸', '.is', 'ISK'),
  ('IT', 'ITA', '380', 'Italy', 'Italian Republic', 'Europe', 'Southern Europe', 'Rome', '+39', '🇮🇹', '.it', 'EUR'),
  ('JE', 'JEY', '832', 'Jersey', 'Bailiwick of Jersey', 'Europe', 'Northern Europe', 'Saint Helier', '+44', '🇯🇪', '.je', 'GBP'),
  ('JM', 'JAM', '388', 'Jamaica', 'Jamaica', 'Americas', 'Caribbean', 'Kingston', '+1876', '🇯🇲', '.jm', 'JMD'),
  ('JO', 'JOR', '400', 'Jordan', 'Hashemite Kingdom of Jordan', 'Asia', 'Western Asia', 'Amman', '+962', '🇯🇴', '.jo', 'JOD'),
  ('JP', 'JPN', '392', 'Japan', 'Japan', 'Asia', 'Eastern Asia', 'Tokyo', '+81', '🇯🇵', '.jp', 'JPY'),
  ('KE', 'KEN', '404', 'Kenya', 'Republic of Kenya', 'Africa', 'Eastern Africa', 'Nairobi', '+254', '🇰🇪', '.ke', 'KES'),
  ('KG', 'KGZ', '417', 'Kyrgyzstan', 'Kyrgyz Republic', 'Asia', 'Central Asia', 'Bishkek', '+996', '🇰🇬', '.kg', 'KGS'),
  ('KH', 'KHM', '116', 'Cambodia', 'Kingdom of Cambodia', 'Asia', 'South-Eastern Asia', 'Phnom Penh', '+855', '🇰🇭', '.kh', 'KHR'),
  ('KI', 'KIR', '296', 'Kiribati', 'Independent and Sovereign Republic of Kiribati', 'Oceania', 'Micronesia', 'South Tarawa', '+686', '🇰🇮', '.ki', 'AUD'),
  ('KM', 'COM', '174', 'Comoros', 'Union of the Comoros', 'Africa', 'Eastern Africa', 'Moroni', '+269', '🇰🇲', '.km', 'KMF'),
  ('KN', 'KNA', '659', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'Americas', 'Caribbean', 'Basseterre', '+1869', '🇰🇳', '.kn', 'XCD'),
  ('KP', 'PRK', '408', 'North Korea', 'Democratic People''s Republic of Korea', 'Asia', 'Eastern Asia', 'Pyongyang', '+850', '🇰🇵', '.kp', 'KPW'),
  ('KR', 'KOR', '410', 'South Korea', 'Republic of Korea', 'Asia', 'Eastern Asia', 'Seoul', '+82', '🇰🇷', '.kr', 'KRW'),
  ('KW', 'KWT', '414', 'Kuwait', 'State of Kuwait', 'Asia', 'Western Asia', 'Kuwait City', '+965', '🇰🇼', '.kw', 'KWD'),
  ('KY', 'CYM', '136', 'Cayman Islands', 'Cayman Islands', 'Americas', 'Caribbean', 'George Town', '+1345', '🇰🇾', '.ky', 'KYD'),
  ('KZ', 'KAZ', '398', 'Kazakhstan', 'Republic of Kazakhstan', 'Asia', 'Central Asia', 'Astana', '+7', '🇰🇿', '.kz', 'KZT'),
  ('LA', 'LAO', '418', 'Laos', 'Lao People''s Democratic Republic', 'Asia', 'South-Eastern Asia', 'Vientiane', '+856', '🇱🇦', '.la', 'LAK'),
  ('LB', 'LBN', '422', 'Lebanon', 'Lebanese Republic', 'Asia', 'Western Asia', 'Beirut', '+961', '🇱🇧', '.lb', 'LBP'),
  ('LC', 'LCA', '662', 'Saint Lucia', 'Saint Lucia', 'Americas', 'Caribbean', 'Castries', '+1758', '🇱🇨', '.lc', 'XCD'),
  ('LI', 'LIE', '438', 'Liechtenstein', 'Principality of Liechtenstein', 'Europe', 'Western Europe', 'Vaduz', '+423', '🇱🇮', '.li', 'CHF'),
  ('LK', 'LKA', '144', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'Asia', 'Southern Asia', 'Colombo', '+94', '🇱🇰', '.lk', 'LKR'),
  ('LR', 'LBR', '430', 'Liberia', 'Republic of Liberia', 'Africa', 'Western Africa', 'Monrovia', '+231', '🇱🇷', '.lr', 'LRD'),
  ('LS', 'LSO', '426', 'Lesotho', 'Kingdom of Lesotho', 'Africa', 'Southern Africa', 'Maseru', '+266', '🇱🇸', '.ls', 'LSL'),
  ('LT', 'LTU', '440', 'Lithuania', 'Republic of Lithuania', 'Europe', 'Northern Europe', 'Vilnius', '+370', '🇱🇹', '.lt', 'EUR'),
  ('LU', 'LUX', '442', 'Luxembourg', 'Grand Duchy of Luxembourg', 'Europe', 'Western Europe', 'Luxembourg', '+352', '🇱🇺', '.lu', 'EUR'),
  ('LV', 'LVA', '428', 'Latvia', 'Republic of Latvia', 'Europe', 'Northern Europe', 'Riga', '+371', '🇱🇻', '.lv', 'EUR'),
  ('LY', 'LBY', '434', 'Libya', 'State of Libya', 'Africa', 'Northern Africa', 'Tripoli', '+218', '🇱🇾', '.ly', 'LYD'),
  ('MA', 'MAR', '504', 'Morocco', 'Kingdom of Morocco', 'Africa', 'Northern Africa', 'Rabat', '+212', '🇲🇦', '.ma', 'MAD'),
  ('MC', 'MCO', '492', 'Monaco', 'Principality of Monaco', 'Europe', 'Western Europe', 'Monaco', '+377', '🇲🇨', '.mc', 'EUR'),
  ('MD', 'MDA', '498', 'Moldova', 'Republic of Moldova', 'Europe', 'Eastern Europe', 'Chișinău', '+373', '🇲🇩', '.md', 'MDL'),
  ('ME', 'MNE', '499', 'Montenegro', 'Montenegro', 'Europe', 'Southeast Europe', 'Podgorica', '+382', '🇲🇪', '.me', 'EUR'),
  ('MF', 'MAF', '663', 'Saint Martin', 'Saint Martin', 'Americas', 'Caribbean', 'Marigot', '+590', '🇲🇫', '.fr', 'EUR'),
  ('MG', 'MDG', '450', 'Madagascar', 'Republic of Madagascar', 'Africa', 'Eastern Africa', 'Antananarivo', '+261', '🇲🇬', '.mg', 'MGA'),
  ('MH', 'MHL', '584', 'Marshall Islands', 'Republic of the Marshall Islands', 'Oceania', 'Micronesia', 'Majuro', '+692', '🇲🇭', '.mh', 'USD'),
  ('MK', 'MKD', '807', 'North Macedonia', 'Republic of North Macedonia', 'Europe', 'Southeast Europe', 'Skopje', '+389', '🇲🇰', '.mk', 'MKD'),
  ('ML', 'MLI', '466', 'Mali', 'Republic of Mali', 'Africa', 'Western Africa', 'Bamako', '+223', '🇲🇱', '.ml', 'XOF'),
  ('MM', 'MMR', '104', 'Myanmar', 'Republic of the Union of Myanmar', 'Asia', 'South-Eastern Asia', 'Naypyidaw', '+95', '🇲🇲', '.mm', 'MMK'),
  ('MN', 'MNG', '496', 'Mongolia', 'Mongolia', 'Asia', 'Eastern Asia', 'Ulan Bator', '+976', '🇲🇳', '.mn', 'MNT'),
  ('MO', 'MAC', '446', 'Macau', 'Macao Special Administrative Region of the People''s Republic of China', 'Asia', 'Eastern Asia', NULL, '+853', '🇲🇴', '.mo', 'MOP'),
  ('MP', 'MNP', '580', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'Oceania', 'Micronesia', 'Saipan', '+1670', '🇲🇵', '.mp', 'USD'),
  ('MQ', 'MTQ', '474', 'Martinique', 'Martinique', 'Americas', 'Caribbean', 'Fort-de-France', '+596', '🇲🇶', '.mq', 'EUR'),
  ('MR', 'MRT', '478', 'Mauritania', 'Islamic Republic of Mauritania', 'Africa', 'Western Africa', 'Nouakchott', '+222', '🇲🇷', '.mr', 'MRU'),
  ('MS', 'MSR', '500', 'Montserrat', 'Montserrat', 'Americas', 'Caribbean', 'Plymouth', '+1664', '🇲🇸', '.ms', 'XCD'),
  ('MT', 'MLT', '470', 'Malta', 'Republic of Malta', 'Europe', 'Southern Europe', 'Valletta', '+356', '🇲🇹', '.mt', 'EUR'),
  ('MU', 'MUS', '480', 'Mauritius', 'Republic of Mauritius', 'Africa', 'Eastern Africa', 'Port Louis', '+230', '🇲🇺', '.mu', 'MUR'),
  ('MV', 'MDV', '462', 'Maldives', 'Republic of the Maldives', 'Asia', 'Southern Asia', 'Malé', '+960', '🇲🇻', '.mv', 'MVR'),
  ('MW', 'MWI', '454', 'Malawi', 'Republic of Malawi', 'Africa', 'Eastern Africa', 'Lilongwe', '+265', '🇲🇼', '.mw', 'MWK'),
  ('MX', 'MEX', '484', 'Mexico', 'United Mexican States', 'Americas', 'North America', 'Mexico City', '+52', '🇲🇽', '.mx', 'MXN'),
  ('MY', 'MYS', '458', 'Malaysia', 'Malaysia', 'Asia', 'South-Eastern Asia', 'Kuala Lumpur', '+60', '🇲🇾', '.my', 'MYR'),
  ('MZ', 'MOZ', '508', 'Mozambique', 'Republic of Mozambique', 'Africa', 'Eastern Africa', 'Maputo', '+258', '🇲🇿', '.mz', 'MZN'),
  ('NA', 'NAM', '516', 'Namibia', 'Republic of Namibia', 'Africa', 'Southern Africa', 'Windhoek', '+264', '🇳🇦', '.na', 'NAD'),
  ('NC', 'NCL', '540', 'New Caledonia', 'New Caledonia', 'Oceania', 'Melanesia', 'Nouméa', '+687', '🇳🇨', '.nc', 'XPF'),
  ('NE', 'NER', '562', 'Niger', 'Republic of Niger', 'Africa', 'Western Africa', 'Niamey', '+227', '🇳🇪', '.ne', 'XOF'),
  ('NF', 'NFK', '574', 'Norfolk Island', 'Territory of Norfolk Island', 'Oceania', 'Australia and New Zealand', 'Kingston', '+672', '🇳🇫', '.nf', 'AUD'),
  ('NG', 'NGA', '566', 'Nigeria', 'Federal Republic of Nigeria', 'Africa', 'Western Africa', 'Abuja', '+234', '🇳🇬', '.ng', 'NGN'),
  ('NI', 'NIC', '558', 'Nicaragua', 'Republic of Nicaragua', 'Americas', 'Central America', 'Managua', '+505', '🇳🇮', '.ni', 'NIO'),
  ('NL', 'NLD', '528', 'Netherlands', 'Kingdom of the Netherlands', 'Europe', 'Western Europe', 'Amsterdam', '+31', '🇳🇱', '.nl', 'EUR'),
  ('NO', 'NOR', '578', 'Norway', 'Kingdom of Norway', 'Europe', 'Northern Europe', 'Oslo', '+47', '🇳🇴', '.no', 'NOK'),
  ('NP', 'NPL', '524', 'Nepal', 'Federal Democratic Republic of Nepal', 'Asia', 'Southern Asia', 'Kathmandu', '+977', '🇳🇵', '.np', 'NPR'),
  ('NR', 'NRU', '520', 'Nauru', 'Republic of Nauru', 'Oceania', 'Micronesia', 'Yaren', '+674', '🇳🇷', '.nr', 'AUD'),
  ('NU', 'NIU', '570', 'Niue', 'Niue', 'Oceania', 'Polynesia', 'Alofi', '+683', '🇳🇺', '.nu', 'NZD'),
  ('NZ', 'NZL', '554', 'New Zealand', 'New Zealand', 'Oceania', 'Australia and New Zealand', 'Wellington', '+64', '🇳🇿', '.nz', 'NZD'),
  ('OM', 'OMN', '512', 'Oman', 'Sultanate of Oman', 'Asia', 'Western Asia', 'Muscat', '+968', '🇴🇲', '.om', 'OMR'),
  ('PA', 'PAN', '591', 'Panama', 'Republic of Panama', 'Americas', 'Central America', 'Panama City', '+507', '🇵🇦', '.pa', 'PAB'),
  ('PE', 'PER', '604', 'Peru', 'Republic of Peru', 'Americas', 'South America', 'Lima', '+51', '🇵🇪', '.pe', 'PEN'),
  ('PF', 'PYF', '258', 'French Polynesia', 'French Polynesia', 'Oceania', 'Polynesia', 'Papeetē', '+689', '🇵🇫', '.pf', 'XPF'),
  ('PG', 'PNG', '598', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'Oceania', 'Melanesia', 'Port Moresby', '+675', '🇵🇬', '.pg', 'PGK'),
  ('PH', 'PHL', '608', 'Philippines', 'Republic of the Philippines', 'Asia', 'South-Eastern Asia', 'Manila', '+63', '🇵🇭', '.ph', 'PHP'),
  ('PK', 'PAK', '586', 'Pakistan', 'Islamic Republic of Pakistan', 'Asia', 'Southern Asia', 'Islamabad', '+92', '🇵🇰', '.pk', 'PKR'),
  ('PL', 'POL', '616', 'Poland', 'Republic of Poland', 'Europe', 'Central Europe', 'Warsaw', '+48', '🇵🇱', '.pl', 'PLN'),
  ('PM', 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'Americas', 'North America', 'Saint-Pierre', '+508', '🇵🇲', '.pm', 'EUR'),
  ('PN', 'PCN', '612', 'Pitcairn Islands', 'Pitcairn Group of Islands', 'Oceania', 'Polynesia', 'Adamstown', '+64', '🇵🇳', '.pn', 'NZD'),
  ('PR', 'PRI', '630', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'Americas', 'Caribbean', 'San Juan', '+1', '🇵🇷', '.pr', 'USD'),
  ('PS', 'PSE', '275', 'Palestine', 'State of Palestine', 'Asia', 'Western Asia', 'Ramallah', '+970', '🇵🇸', '.ps', 'EGP'),
  ('PT', 'PRT', '620', 'Portugal', 'Portuguese Republic', 'Europe', 'Southern Europe', 'Lisbon', '+351', '🇵🇹', '.pt', 'EUR'),
  ('PW', 'PLW', '585', 'Palau', 'Republic of Palau', 'Oceania', 'Micronesia', 'Ngerulmud', '+680', '🇵🇼', '.pw', 'USD'),
  ('PY', 'PRY', '600', 'Paraguay', 'Republic of Paraguay', 'Americas', 'South America', 'Asunción', '+595', '🇵🇾', '.py', 'PYG'),
  ('QA', 'QAT', '634', 'Qatar', 'State of Qatar', 'Asia', 'Western Asia', 'Doha', '+974', '🇶🇦', '.qa', 'QAR'),
  ('RE', 'REU', '638', 'Réunion', 'Réunion Island', 'Africa', 'Eastern Africa', 'Saint-Denis', '+262', '🇷🇪', '.re', 'EUR'),
  ('RO', 'ROU', '642', 'Romania', 'Romania', 'Europe', 'Southeast Europe', 'Bucharest', '+40', '🇷🇴', '.ro', 'RON'),
  ('RS', 'SRB', '688', 'Serbia', 'Republic of Serbia', 'Europe', 'Southeast Europe', 'Belgrade', '+381', '🇷🇸', '.rs', 'RSD'),
  ('RU', 'RUS', '643', 'Russia', 'Russian Federation', 'Europe', 'Eastern Europe', 'Moscow', '+7', '🇷🇺', '.ru', 'RUB'),
  ('RW', 'RWA', '646', 'Rwanda', 'Republic of Rwanda', 'Africa', 'Eastern Africa', 'Kigali', '+250', '🇷🇼', '.rw', 'RWF'),
  ('SA', 'SAU', '682', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'Asia', 'Western Asia', 'Riyadh', '+966', '🇸🇦', '.sa', 'SAR'),
  ('SB', 'SLB', '090', 'Solomon Islands', 'Solomon Islands', 'Oceania', 'Melanesia', 'Honiara', '+677', '🇸🇧', '.sb', 'SBD'),
  ('SC', 'SYC', '690', 'Seychelles', 'Republic of Seychelles', 'Africa', 'Eastern Africa', 'Victoria', '+248', '🇸🇨', '.sc', 'SCR'),
  ('SD', 'SDN', '729', 'Sudan', 'Republic of the Sudan', 'Africa', 'Northern Africa', 'Khartoum', '+249', '🇸🇩', '.sd', 'SDG'),
  ('SE', 'SWE', '752', 'Sweden', 'Kingdom of Sweden', 'Europe', 'Northern Europe', 'Stockholm', '+46', '🇸🇪', '.se', 'SEK'),
  ('SG', 'SGP', '702', 'Singapore', 'Republic of Singapore', 'Asia', 'South-Eastern Asia', 'Singapore', '+65', '🇸🇬', '.sg', 'SGD'),
  ('SH', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', 'Western Africa', 'Jamestown', '+2', '🇸🇭', '.sh', 'GBP'),
  ('SI', 'SVN', '705', 'Slovenia', 'Republic of Slovenia', 'Europe', 'Central Europe', 'Ljubljana', '+386', '🇸🇮', '.si', 'EUR'),
  ('SJ', 'SJM', '744', 'Svalbard and Jan Mayen', 'Svalbard og Jan Mayen', 'Europe', 'Northern Europe', 'Longyearbyen', '+4779', '🇸🇯', '.sj', 'NOK'),
  ('SK', 'SVK', '703', 'Slovakia', 'Slovak Republic', 'Europe', 'Central Europe', 'Bratislava', '+421', '🇸🇰', '.sk', 'EUR'),
  ('SL', 'SLE', '694', 'Sierra Leone', 'Republic of Sierra Leone', 'Africa', 'Western Africa', 'Freetown', '+232', '🇸🇱', '.sl', NULL),
  ('SM', 'SMR', '674', 'San Marino', 'Most Serene Republic of San Marino', 'Europe', 'Southern Europe', 'City of San Marino', '+378', '🇸🇲', '.sm', 'EUR'),
  ('SN', 'SEN', '686', 'Senegal', 'Republic of Senegal', 'Africa', 'Western Africa', 'Dakar', '+221', '🇸🇳', '.sn', 'XOF'),
  ('SO', 'SOM', '706', 'Somalia', 'Federal Republic of Somalia', 'Africa', 'Eastern Africa', 'Mogadishu', '+252', '🇸🇴', '.so', 'SOS'),
  ('SR', 'SUR', '740', 'Suriname', 'Republic of Suriname', 'Americas', 'South America', 'Paramaribo', '+597', '🇸🇷', '.sr', 'SRD'),
  ('SS', 'SSD', '728', 'South Sudan', 'Republic of South Sudan', 'Africa', 'Middle Africa', 'Juba', '+211', '🇸🇸', '.ss', 'SSP'),
  ('ST', 'STP', '678', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'Africa', 'Middle Africa', 'São Tomé', '+239', '🇸🇹', '.st', 'STN'),
  ('SV', 'SLV', '222', 'El Salvador', 'Republic of El Salvador', 'Americas', 'Central America', 'San Salvador', '+503', '🇸🇻', '.sv', 'USD'),
  ('SX', 'SXM', '534', 'Sint Maarten', 'Sint Maarten', 'Americas', 'Caribbean', 'Philipsburg', '+1721', '🇸🇽', '.sx', 'ANG'),
  ('SY', 'SYR', '760', 'Syria', 'Syrian Arab Republic', 'Asia', 'Western Asia', 'Damascus', '+963', '🇸🇾', '.sy', 'SYP'),
  ('SZ', 'SWZ', '748', 'Eswatini', 'Kingdom of Eswatini', 'Africa', 'Southern Africa', 'Lobamba', '+268', '🇸🇿', '.sz', 'SZL'),
  ('TC', 'TCA', '796', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'Americas', 'Caribbean', 'Cockburn Town', '+1649', '🇹🇨', '.tc', 'USD'),
  ('TD', 'TCD', '148', 'Chad', 'Republic of Chad', 'Africa', 'Middle Africa', 'N''Djamena', '+235', '🇹🇩', '.td', 'XAF'),
  ('TF', 'ATF', '260', 'French Southern and Antarctic Lands', 'Territory of the French Southern and Antarctic Lands', 'Antarctic', NULL, 'Port-aux-Français', '+262', '🇹🇫', '.tf', 'EUR'),
  ('TG', 'TGO', '768', 'Togo', 'Togolese Republic', 'Africa', 'Western Africa', 'Lomé', '+228', '🇹🇬', '.tg', 'XOF'),
  ('TH', 'THA', '764', 'Thailand', 'Kingdom of Thailand', 'Asia', 'South-Eastern Asia', 'Bangkok', '+66', '🇹🇭', '.th', 'THB'),
  ('TJ', 'TJK', '762', 'Tajikistan', 'Republic of Tajikistan', 'Asia', 'Central Asia', 'Dushanbe', '+992', '🇹🇯', '.tj', 'TJS'),
  ('TK', 'TKL', '772', 'Tokelau', 'Tokelau', 'Oceania', 'Polynesia', 'Fakaofo', '+690', '🇹🇰', '.tk', 'NZD'),
  ('TL', 'TLS', '626', 'Timor-Leste', 'Democratic Republic of Timor-Leste', 'Asia', 'South-Eastern Asia', 'Dili', '+670', '🇹🇱', '.tl', 'USD'),
  ('TM', 'TKM', '795', 'Turkmenistan', 'Turkmenistan', 'Asia', 'Central Asia', 'Ashgabat', '+993', '🇹🇲', '.tm', 'TMT'),
  ('TN', 'TUN', '788', 'Tunisia', 'Tunisian Republic', 'Africa', 'Northern Africa', 'Tunis', '+216', '🇹🇳', '.tn', 'TND'),
  ('TO', 'TON', '776', 'Tonga', 'Kingdom of Tonga', 'Oceania', 'Polynesia', 'Nuku''alofa', '+676', '🇹🇴', '.to', 'TOP'),
  ('TR', 'TUR', '792', 'Türkiye', 'Republic of Türkiye', 'Asia', 'Western Asia', 'Ankara', '+90', '🇹🇷', '.tr', 'TRY'),
  ('TT', 'TTO', '780', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'Americas', 'Caribbean', 'Port of Spain', '+1868', '🇹🇹', '.tt', 'TTD'),
  ('TV', 'TUV', '798', 'Tuvalu', 'Tuvalu', 'Oceania', 'Polynesia', 'Funafuti', '+688', '🇹🇻', '.tv', 'AUD'),
  ('TW', 'TWN', '158', 'Taiwan', 'Republic of China (Taiwan)', 'Asia', 'Eastern Asia', 'Taipei', '+886', '🇹🇼', '.tw', 'TWD'),
  ('TZ', 'TZA', '834', 'Tanzania', 'United Republic of Tanzania', 'Africa', 'Eastern Africa', 'Dodoma', '+255', '🇹🇿', '.tz', 'TZS'),
  ('UA', 'UKR', '804', 'Ukraine', 'Ukraine', 'Europe', 'Eastern Europe', 'Kyiv', '+380', '🇺🇦', '.ua', 'UAH'),
  ('UG', 'UGA', '800', 'Uganda', 'Republic of Uganda', 'Africa', 'Eastern Africa', 'Kampala', '+256', '🇺🇬', '.ug', 'UGX'),
  ('UM', 'UMI', '581', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'Americas', 'North America', NULL, '+268', '🇺🇲', '.us', 'USD'),
  ('US', 'USA', '840', 'United States', 'United States of America', 'Americas', 'North America', 'Washington D.C.', '+1', '🇺🇸', '.us', 'USD'),
  ('UY', 'URY', '858', 'Uruguay', 'Oriental Republic of Uruguay', 'Americas', 'South America', 'Montevideo', '+598', '🇺🇾', '.uy', 'UYU'),
  ('UZ', 'UZB', '860', 'Uzbekistan', 'Republic of Uzbekistan', 'Asia', 'Central Asia', 'Tashkent', '+998', '🇺🇿', '.uz', 'UZS'),
  ('VA', 'VAT', '336', 'Vatican City', 'Vatican City State', 'Europe', 'Southern Europe', 'Vatican City', '+3', '🇻🇦', '.va', 'EUR'),
  ('VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'Americas', 'Caribbean', 'Kingstown', '+1784', '🇻🇨', '.vc', 'XCD'),
  ('VE', 'VEN', '862', 'Venezuela', 'Bolivarian Republic of Venezuela', 'Americas', 'South America', 'Caracas', '+58', '🇻🇪', '.ve', 'VES'),
  ('VG', 'VGB', '092', 'British Virgin Islands', 'Virgin Islands', 'Americas', 'Caribbean', 'Road Town', '+1284', '🇻🇬', '.vg', 'USD'),
  ('VI', 'VIR', '850', 'United States Virgin Islands', 'Virgin Islands of the United States', 'Americas', 'Caribbean', 'Charlotte Amalie', '+1340', '🇻🇮', '.vi', 'USD'),
  ('VN', 'VNM', '704', 'Vietnam', 'Socialist Republic of Vietnam', 'Asia', 'South-Eastern Asia', 'Hanoi', '+84', '🇻🇳', '.vn', 'VND'),
  ('VU', 'VUT', '548', 'Vanuatu', 'Republic of Vanuatu', 'Oceania', 'Melanesia', 'Port Vila', '+678', '🇻🇺', '.vu', 'VUV'),
  ('WF', 'WLF', '876', 'Wallis and Futuna', 'Territory of the Wallis and Futuna Islands', 'Oceania', 'Polynesia', 'Mata-Utu', '+681', '🇼🇫', '.wf', 'XPF'),
  ('WS', 'WSM', '882', 'Samoa', 'Independent State of Samoa', 'Oceania', 'Polynesia', 'Apia', '+685', '🇼🇸', '.ws', 'WST'),
  ('XK', 'UNK', '', 'Kosovo', 'Republic of Kosovo', 'Europe', 'Southeast Europe', 'Pristina', '+383', '🇽🇰', '.xk', 'EUR'),
  ('YE', 'YEM', '887', 'Yemen', 'Republic of Yemen', 'Asia', 'Western Asia', 'Sana''a', '+967', '🇾🇪', '.ye', 'YER'),
  ('YT', 'MYT', '175', 'Mayotte', 'Department of Mayotte', 'Africa', 'Eastern Africa', 'Mamoudzou', '+262', '🇾🇹', '.yt', 'EUR'),
  ('ZA', 'ZAF', '710', 'South Africa', 'Republic of South Africa', 'Africa', 'Southern Africa', 'Pretoria', '+27', '🇿🇦', '.za', 'ZAR'),
  ('ZM', 'ZMB', '894', 'Zambia', 'Republic of Zambia', 'Africa', 'Eastern Africa', 'Lusaka', '+260', '🇿🇲', '.zm', 'ZMW'),
  ('ZW', 'ZWE', '716', 'Zimbabwe', 'Republic of Zimbabwe', 'Africa', 'Eastern Africa', 'Harare', '+263', '🇿🇼', '.zw', 'BWP');

CREATE TRIGGER countries_immutable
BEFORE INSERT OR UPDATE OR DELETE ON public.countries
FOR EACH ROW EXECUTE FUNCTION public.prevent_row_mutation();

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app') THEN
    GRANT SELECT ON public.countries TO app;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'admin_service') THEN
    GRANT SELECT ON public.countries TO admin_service;
  END IF;
END;
$$;
