import { Section } from 'react-email'
import { DEFAULT_LOCALE } from '@workspace/core/i18n'

import { EmailButton } from '../components/email-button'
import { EmailLayout } from '../components/email-layout'
import { EmailHeading, EmailText } from '../components/email-typography'
import { emailMessages, type EmailLocale } from '../i18n'
import { emailTokens } from '../tokens'

export interface PasswordResetProps {
  /** Password-reset URL generated by BetterAuth. */
  resetUrl: string
  /** App name (defaults to "App" — override per project). */
  appName?: string
  /** Recipient's language (defaults to the app default). */
  locale?: EmailLocale
}

/**
 * Sent when a user requests a password reset. Copy lives in `../i18n.ts`.
 */
export function PasswordReset({
  resetUrl,
  appName = 'App',
  locale = DEFAULT_LOCALE,
}: PasswordResetProps) {
  const t = emailMessages(locale)
  const m = t.passwordReset

  return (
    <EmailLayout preview={m.preview(appName)} appName={appName} locale={locale}>
      <EmailHeading>{m.heading}</EmailHeading>

      <EmailText>{m.body(appName)}</EmailText>

      <EmailButton href={resetUrl}>{m.cta}</EmailButton>

      <EmailText muted small>
        {m.expiry} {m.ignore}
      </EmailText>

      <Section
        style={{
          background: emailTokens.colors.muted,
          borderRadius: emailTokens.radii.md,
          padding: '16px',
          marginTop: '8px',
        }}
      >
        <EmailText muted small>
          {t.common.linkFallback}
        </EmailText>
        <EmailText small>
          <a
            href={resetUrl}
            style={{
              color: emailTokens.colors.brand,
              wordBreak: 'break-all' as const,
            }}
          >
            {resetUrl}
          </a>
        </EmailText>
      </Section>
    </EmailLayout>
  )
}

/** Default export required by React Email preview server. */
export default PasswordReset

PasswordReset.PreviewProps = {
  resetUrl: 'https://example.com/api/auth/reset-password?token=abc123',
  appName: 'App',
  locale: DEFAULT_LOCALE,
} satisfies PasswordResetProps
