import { Section } from 'react-email'
import { DEFAULT_LOCALE } from '@workspace/core/i18n'

import { EmailButton } from '../components/email-button'
import { EmailLayout } from '../components/email-layout'
import { EmailHeading, EmailText } from '../components/email-typography'
import { emailMessages, type EmailLocale } from '../i18n'
import { emailTokens } from '../tokens'

export interface RegistrationConfirmationProps {
  /** Full name of the new user. */
  name: string
  /** Verification URL generated by BetterAuth. */
  verificationUrl: string
  /** App name (defaults to "App" — override per project). */
  appName?: string
  /** Recipient's language (defaults to the app default). */
  locale?: EmailLocale
}

/**
 * Sent when a new user registers. Asks them to verify their email address.
 *
 * HOW TO CUSTOMISE:
 *   1. Adjust the copy in `../i18n.ts` (one place per language).
 *   2. Update `emailTokens` in `../tokens.ts` to match your brand colours.
 *   3. Run `pnpm email:preview` to preview in a browser + email client.
 */
export function RegistrationConfirmation({
  name,
  verificationUrl,
  appName = 'App',
  locale = DEFAULT_LOCALE,
}: RegistrationConfirmationProps) {
  const t = emailMessages(locale)
  const m = t.registration

  return (
    <EmailLayout preview={m.preview(appName)} appName={appName} locale={locale}>
      <EmailHeading>{m.heading(name)}</EmailHeading>

      <EmailText>{m.body(appName)}</EmailText>

      <EmailButton href={verificationUrl}>{m.cta}</EmailButton>

      <EmailText muted small>
        {m.expiry}
      </EmailText>

      <Section
        style={{
          background: emailTokens.colors.muted,
          borderRadius: emailTokens.radii.md,
          padding: '16px',
          marginTop: '8px',
        }}
      >
        <EmailText muted small>
          {t.common.linkFallback}
        </EmailText>
        <EmailText small>
          <a
            href={verificationUrl}
            style={{
              color: emailTokens.colors.brand,
              wordBreak: 'break-all' as const,
            }}
          >
            {verificationUrl}
          </a>
        </EmailText>
      </Section>
    </EmailLayout>
  )
}

/** Default export required by React Email preview server. */
export default RegistrationConfirmation

RegistrationConfirmation.PreviewProps = {
  name: 'Marie Dupont',
  verificationUrl: 'https://example.com/api/auth/verify-email?token=abc123',
  appName: 'App',
  locale: DEFAULT_LOCALE,
} satisfies RegistrationConfirmationProps
