import { Section } from '@react-email/components'

import { EmailButton } from '../components/email-button'
import { EmailLayout } from '../components/email-layout'
import { EmailHeading, EmailText } from '../components/email-typography'
import { emailTokens } from '../tokens'

export interface RegistrationConfirmationProps {
  /** Full name of the new user. */
  name: string
  /** Verification URL generated by BetterAuth. */
  verificationUrl: string
  /** App name (defaults to "App" — override per project). */
  appName?: string
}

/**
 * Sent when a new user registers. Asks them to verify their email address.
 *
 * HOW TO CUSTOMISE:
 *   1. Update `appName` to your product name (or pass it as a prop).
 *   2. Adjust the copy in the heading, body text, and button.
 *   3. Update `emailTokens` in `src/tokens.ts` to match your brand colours.
 *   4. Run `pnpm email:preview` to preview in a browser + email client.
 */
export function RegistrationConfirmation({
  name,
  verificationUrl,
  appName = 'App',
}: RegistrationConfirmationProps) {
  return (
    <EmailLayout
      preview={`Bienvenue sur ${appName} — confirmez votre adresse e-mail`}
      appName={appName}
    >
      <EmailHeading>Bienvenue, {name} 👋</EmailHeading>

      <EmailText>
        Merci de vous être inscrit sur <strong>{appName}</strong>. Pour activer
        votre compte, veuillez confirmer votre adresse e-mail en cliquant sur le
        bouton ci-dessous.
      </EmailText>

      <EmailButton href={verificationUrl}>
        Confirmer mon adresse e-mail
      </EmailButton>

      <EmailText muted small>
        Ce lien expire dans 1 heure. Si vous n&apos;avez pas créé de compte,
        vous pouvez ignorer cet e-mail en toute sécurité.
      </EmailText>

      <Section
        style={{
          background: emailTokens.colors.muted,
          borderRadius: emailTokens.radii.md,
          padding: '16px',
          marginTop: '8px',
        }}
      >
        <EmailText muted small>
          Si le bouton ne fonctionne pas, copiez et collez ce lien dans votre
          navigateur :
        </EmailText>
        <EmailText small>
          <a
            href={verificationUrl}
            style={{
              color: emailTokens.colors.brand,
              wordBreak: 'break-all' as const,
            }}
          >
            {verificationUrl}
          </a>
        </EmailText>
      </Section>
    </EmailLayout>
  )
}

/** Default export required by React Email preview server. */
export default RegistrationConfirmation

RegistrationConfirmation.PreviewProps = {
  name: 'Marie Dupont',
  verificationUrl: 'https://example.com/api/auth/verify-email?token=abc123',
  appName: 'App',
} satisfies RegistrationConfirmationProps
